---
- name: setup rhel server
  hosts: all
  remote_user: root
  #remote_user: user
  #become: yes
  #become_method: sudo

  roles:
    - common
    #- pip
    - sudo
    - users
    - sshkeys
    #- networking
