---
- name: install packages for rhel
  package:
    name:
      - cockpit
     #- podman
      - curl
      - wget
      - python2
      - python3
      - python3-pip
      - git
      - vim
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - oracle-epel-release-el8
      - sudo
      - bash-completion
      - virt-top
      - libguestfs-tools
        #- centos-release-scl-rh
        #- centos-release-scl
    state: present

- name: Install the virt package group
  yum:
    name: "@virt"
    state: present




#- name: add group for lxd
#  group:
#    name: lxd
#    state: present
